### ISSUE TITLE
Strange behavior of balls

### ISSUE THREAD

**Issue by artyom-ivanov** [MTrajK/bouncing-balls#1]
@MTrajK thx for your code :) Im find some strange thing: if the bottom line is completely filled with balls, then the balls are shaking.
![CxeG3Sh2qTRzVbcCjkd_pebkPNvWwie5](https://user-images.githubusercontent.com/12496849/74218792-5addae80-4cc4-11ea-9f3b-0df4356de2b3.gif)

**Comment by MTrajK** [comment]
Hi @artyom-ivanov thank you too, I saw this bug 2 days ago and I'm planning to fix it these days. There is a problem with collisions because there is no more space on the bottom and the balls are trying to go down ( but they don't know about the balls under them :/ ).

**Comment by MTrajK** [comment]
This bug with shaking balls (and balls going below the bottom) is fixed in the last commit [abf6a69
](https://github.com/MTrajK/bouncing-balls/commit/abf6a694d766ca71529ba05d31be002f5bb91dec). Simple fix, first checks for a collision and after that moves the ball (previously, it was moving the ball first and after that checking for a collision). 
But there is still one more bug when the bottom line is completely filled, then the balls aren't stacking (one over another), they are disappearing. At this moment I have a brute force solution, I'll think about a new, smarter one.
