### ISSUE TITLE
The dancing balls problem

### ISSUE THREAD

**Issue by noncom** [MTrajK/bouncing-balls#5]
Hello! I find that with this code (both in your demo and in my re-implementation in my program) there happens to be the problem of the "dancing balls". Sometimes balls that come into contact start "dancing" around each other instead of bouncing.

As I have found out that happens because in certain circumstances the collided balls do not get repositoned outside each other correctly. The error is in these two lines:
https://github.com/MTrajK/bouncing-balls/blob/9edad0fa2ce64f5641879ff3f6075cfb41ec9b41/src/js/balls.js#L56-L57

it should instead be 
```javascript
    this.position = this.position.add((this.position - ball.position).tryNormalize().mult(diff));
    ball.position = ball.position.add((ball.position - this.position).tryNormalize().mult(diff));
```

So that we reposition the balls not in their speeds directions, which might be directed anywhere and won't always take the balls to positions where they separate. But rather in the direction of a line that passes through both of their centers, in opposite directions, effectively pulling them away from each other.

**Comment by MTrajK** [comment]
Hi, you're right, something like:
```javascript
this.position = this.position.add(this.position.sub(ball.position).tryNormalize().mult(diff));
ball.position = ball.position.add(ball.position.sub(this.position).tryNormalize().mult(diff));
```
is more logical in this situation, also I won't need 'applyRandomVector', but this solution still doesn't solve the "dancing balls".
Also I think that's not how the natural collision works because the balls won't continue in those directions (because of that I'm computing the new velocity).

But now I think I have a better and smarter idea.
Currently, we're calculating the newer velocities and after that, the balls are moved outside of the collision. The schedule should be changed, first move the balls outside the collision using the older velocities (move them back, in this way we'll be sure that the balls are outside of the collision), and after that compute the newer velocities.

![Untitled](https://user-images.githubusercontent.com/7501012/87043265-0e57ba00-c1f5-11ea-9061-4eceb8376025.png)

**Comment by MTrajK** [comment]
Hi, I implemented the idea from the picture. There is a new method in balls.js, called moveBallsOutOfCollision, and I can't see the dancing balls problem anymore.
